-- Crea la tabla de historial de evaluaciones resueltas por los estudiantes.
CREATE TABLE respuestas_estudiante (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario bigint REFERENCES usuario(id),
  id_tema bigint REFERENCES temas(id),
  puntaje int NOT NULL,
  total_preguntas int NOT NULL,
  respuestas_correctas int NOT NULL,
  fecha timestamp with time zone DEFAULT now()
);

ALTER TABLE respuestas_estudiante ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura propia"
  ON respuestas_estudiante FOR SELECT
  USING (true);

CREATE POLICY "Permitir insercion"
  ON respuestas_estudiante FOR INSERT
  WITH CHECK (true);